version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - kafka
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
